import React from "react";
import { useSelector, useDispatch } from "react-redux";
import WeightLogModal from "../WeightLogModal";
import OpenModalButton from "../OpenModalButton";
import { useSelectedDate } from "../../context/SelectedDate";
import { formattingUserInputDate } from "../../utils";
import { getAllWeightLogForADayThunk } from "../../store/weightLogs";
import { useRemoveStrengthLog } from "../../utils";
import { useEffect } from "react";
import "../Diary/Diary.css";
